Añadir Hook de UseCourses para traer datos de curso y estudiantes de un profesor a través de un id.
aleperea17/NucleoIDS pull request #23
Opened 2024-10-28 01:11 UTC by FacuMa02

### Como probar el hook
ir a `frontend` > `npm run dev` dirigirse a la ruta http://localhost:5173/professor-course 
trae los datos de un profesor particular (id = c1a71932-a697-4fe6-8833-f6de424b82cb) que está hardcodeado solo para pruebas. Lo hice así porque lo importante es que el hook lo recibe como parámetro de una query (de hecho, RECOMIENDO que una vez finalice la prueba, se elimine el componente creado para probarlo, llamado `ProfessorCourseDetails.jsx` dentro de la carpeta table y también eliminar este componente de routes.jsx )

2024-10-28 01:27 UTC, FacuMa02 commented
Importante detalle: en el Hook, está puesta la dirección localhost:8000 que también está hardcodeada porque no supe poner la dirección desde las variables de entorno del front. @ArtuArtaza cuando lo uses podrías cambiar eso por la referencia correcta?

2024-10-28 01:33 UTC, aleperea17 approved these changes
Funciona perfecto!

2024-10-28 01:54 UTC, ArtuArtaza requested changes

2024-10-28 01:54 UTC, ArtuArtaza commented on frontend/src/hooks/useCourse.js
> +        const response = await fetch(`http://localhost:8000/courses/get-course-by-professor-id?professor_id=${professorId}`, {
Dos cosas que podrías modificar acá:
- Omite el http://localhost:8000 y remplazalo por la concatenación de la variable de entorno `VITE_PUBLIC_API_URL`
- No utilices fetch. Ya esta mergeado el nuevo fetcher, que hace la petición del refresh token asi no tenes que andarle pasando el token al header.
el fetcher esta en src/fetcher/fetcher.js
Tienes un ejemplo de como usarlo en el hook useUsers
Nosotros ya manejamos una variable de entorno para el frontend que se llama:

2024-10-28 01:54 UTC, ArtuArtaza commented on frontend/src/hooks/useCourse.js
> +  useEffect(() => {
No hagas la llamada en el useEffect, para eso tenemos una libreria llamada `useSWR` que se encarga de hacer la
llamada, solo importa al hook, y le pasas el url como primer parametro y la función que hace el fetch en el segundo llamado.
Tienes un ejemplo en el useUsers también.

2024-10-28 01:54 UTC, ArtuArtaza commented on backend/src/controllers/courses_controller.py
> +@router.get("/get-course-by-professor-id")
Esta ruta debería estar protegida.

2024-10-28 12:23 UTC, FacuMa02 commented on backend/src/controllers/courses_controller.py
> +@router.get("/get-course-by-professor-id")
Ya pude cambiar todas las sugerencias, el problema es que no sé como extraer el token para que pueda acceder a la información que necesito desde el front. Tengo que usar el hook de localStorage que está creado? Como se usa?

2024-10-28 14:39 UTC, ArtuArtaza commented on backend/src/controllers/courses_controller.py
> +@router.get("/get-course-by-professor-id")
Nonono
usando el fetcher que hice ya pasa el token solo

2024-10-28 17:38 UTC, FacuMa02 commented
Cambios agregados.

2024-10-30 21:01 UTC, ArtuArtaza approved these changes

2024-10-30 21:05 UTC, merged